### ISSUE TITLE
feature request: time & date picker

### ISSUE THREAD

**Issue by ramarro123** [mdbootstrap/mdb-ui-kit#1005]
any plan to add support something like that
http://www.material-ui.com/#/components/date-picker

and
http://www.material-ui.com/#/components/time-picker

the google guideline for picker it's locate here
https://www.google.com/design/spec/components/pickers.html#

will be very nice to have it without having to use a different project for that :)

**Comment by FezVrasta** [comment]
@rosskevin has a plugin to do that, not sure if it's finished yet

**Comment by rosskevin** [comment]
Here is one for BMD v4, since it accepts templates, you should be able to create one for v3 that is very similar to the v4 one.
http://alienfast.github.io/picker.js/

I'm moving on but this project is a great basis for enhancement, freshly refactored, well tested and ready for additional maintainers to take it over.

More info at:
https://github.com/alienfast/picker.js

**Comment by PersoRu** [comment]
Hi @rosskevin ,

This one doesn't include a timepicker? Do you also have a solution for this?
Thanks in advance.

**Comment by japita-se** [comment]
MD does not support bootstrap-datepicker?
