### ISSUE TITLE
v3 ArriveJS jquery dependency

### ISSUE THREAD

**Issue by leolorenzoluis** [mdbootstrap/mdb-ui-kit#1006]
#### Summary

Using https://cdnjs.com/libraries/bootstrap-material-design/0.5.9 with any browser, it throws when init is called
`material.js:315 Uncaught TypeError: $document.arrive is not a function`

document.arrive is not null but $document.arrive is null, where $document is assigned as $(document)
#### Expected result

I'm expecting that V3 would support ArriveJS
#### Additional Information

https://github.com/FezVrasta/bootstrap-material-design/pull/689/commits/11fb4e3b97a7da1679093fa7fa08293886b9d19f

**Comment by rosskevin** [comment]
Please recreate with our codepen (as requested), not some external source.

**Comment by jgolieb** [comment]
This problem seems to occur when jQuery and arrive.js are not loaded in the expected order.  If Arrive does not detect $, then it will not install as a jQuery plugin.  Material.js assumes that if arrive.js is loaded at all (at document.arrive) then it is also installed as a jQuery plugin (at $(document).arrive), which makes sense from the Bootstrap perspective, since jQuery is a Bootstrap dependency.  However, it is obviously possible for this not to be the case, leading to this bug.  It would probably be safer for material.js to check for the presence of arrive.js by just checking $(document).arrive.

I had this problem when using Webpack and resolved it by adding the following to my webpack.config.js to ensure that arrive.js finds $:

`plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ]`
