### ISSUE TITLE
Simplify build

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1167]
Right now our build uses Gulp 4 and some custom stuff...

I would like to simplify it to use just npm scripts and nothing more.

**Comment by Toilal** [comment]
I do agree that gulp and many other build systems often bring more issues and complexity than what they try to solve. You should consider webpack though, it's more like a development and packaging tool than others.

But if you really think that only npm scripts can do the job, just use this only.

**Comment by FezVrasta** [comment]
The problem with Webpack is that it doesn't create lightweight bundles. Rollup is recommended for bundling libraries.

**Comment by Toilal** [comment]
Webpack 2 now supports Tree Shaking, so it should be quite the same (even if there's still some issues with the feature, [this one is worth reading](https://github.com/webpack/webpack/issues/2867)).

**Comment by FezVrasta** [comment]
Webpack adds a lot of extra code needed to make it work. It's something the developers behind it know and they suggest Rollup as well for this reason if one needs to bundle a library. (I asked them)

**Comment by ghost** [comment]
Rolling your own build pipeline would likely simplify things considerably. [I've seen](https://github.com/jupl/btc-chaplin/tree/master/jakelib) Jake work well for boilerplates managing their own build pipeline with NPM tasks before Gulp even became a thing.

On the bundler front, adding Webpack or Babel tends to translate into developer pain. If you can avoid that complexity, I'm sure your stargazers would appreciate it. And that'll leave your users to choose the asset pipeline which best meets their needs.

Also, because Bootstrap 4 includes more script dependencies and will slow down sites, I believe you may find this of some value: https://hackcabin.com/post/managing-async-dependencies-javascript/

**Aside**

> Webpack 2 now supports Tree Shaking

@Toilal Could you point a reference validating that statement? AFIAK Tree Shaking is still not functional in Webpack 2, which is as good as not existing at all. (I've read through the entire linked thread, by the way. It saddened me.)

**Comment by Toilal** [comment]
There's many resources about Webpack 2 Tree Shaking. It's a new feature that was not there in Webpack 1, so beware if you find older materials.

A sample app, Tree Shaking ready, using Webpack 2 : https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2

Some blog post:
https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233
https://medium.freecodecamp.com/tree-shaking-es6-modules-in-webpack-2-1add6672f31b

Also angular does Tree Shaking inside angular-cli which embed Webpack 2 too (mentionned in this issue : https://github.com/angular/angular-cli/issues/2901).

**Comment by ghost** [comment]
Thanks for the info. I've [asked Sean Larkin](https://medium.com/@jhabdas/sean-thanks-for-your-continued-work-on-webpack-465572df6208?source=linkShare-d4a43ea991d3-1490470187) directly on Medium, where Tree Shaking was formally announced, about the status of tree shaking, and linked to two critical blocking WebPack tree shaking issues I found scrubbing your list. Appreciate the breadcrumbs.

**Comment by ghost** [comment]
@FezVrasta Thoughts on using Fetch Injection to [load Bootstrap resources in parallel](https://github.com/twbs/bootstrap/issues/22139#issuecomment-290935004) with the tooling simplification? I'd like to update the lib for a scaled real world scenario, and could use the feedback. I'd love to hear your thoughts.

**Comment by FezVrasta** [comment]
done. no gulp, grunt, stfu nor anything. just two npm scripts.

**Comment by ghost** [comment]
![confettimustache](https://user-images.githubusercontent.com/440298/29239145-2c88d638-7f79-11e7-8ead-b3378eba6957.gif)
