### ISSUE TITLE
Add support for $theme-colors override

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1265]
Right now we don't make use of `$theme-colors` to style our components, this makes it hard to override them.

We should change the way we color our components to support the `$theme-colors` map as Bootstrap v4 does.

I'm not a SCSS wizard, so contributions are welcome.

**Comment by spiotr12** [comment]
+1 
I just tried to change the colors and I field. Looking forward for implementation. Can't you just use it as bootstrap 4? 

Issues I had:
- `$theme-color` not overriding all colors. e.g. `$theme-color: { primary: red }` would not work for buttons. I had to separately override `$brand-primary`
- Cannot override secondary color
**EDIT**
Secondary is hardcoded

**Comment by spiotr12** [comment]
My quick solution:
```
$theme-colors: (
  primary: $pm-primary, // my custom color
  secondary: $pm-secondary, // my custom color
  //success: $success,
  //info: $info,
  //warning: $warning,
  //danger: $danger,
  //light: $light,
  //dark: $dark
);

$brand-primary: map_get($theme-colors, primary);
$brand-success: map_get($theme-colors, success);
$brand-danger: map_get($theme-colors, danger);
$brand-warning: map_get($theme-colors, warning);
$brand-info: map_get($theme-colors, info);
```
However it would bo good to customize all colors - if anyone would need it.

**Comment by spiotr12** [comment]
I've created branch where there colors are used from theme-colors: [customizable-colors](https://github.com/spiotr12/bootstrap-material-design/tree/customizable-colors)

If you would be happy for these changes, I gladly contribute to your project

Thanks for any feedback.

**Comment by FezVrasta** [comment]
Thanks, that's great! Please feel free to submit a PR with your changes and I'll review it

**Comment by spiotr12** [comment]
PR waiting for review 😄

**Comment by vinyanalista** [comment]
I tried to build a custom version of BMD using `$blue-300` (`#64B5F6`) as primary color. Despite the CSS was built, the primary color was still the default one (`$teal`, `#009688`). I'm not a NPM nor a SCSS expert, so I ask for help.

Here is what I did since the beginning (following this issue, the pull request #1273 and the file [HACKING.md](https://github.com/FezVrasta/bootstrap-material-design/blob/v4.1.1/HACKING.md):

```
$ git clone https://github.com/FezVrasta/bootstrap-material-design.git
$ git checkout v4.1.1
$ npm install
```

I edited the file [scss/bootstrap-material-design.scss](https://github.com/FezVrasta/bootstrap-material-design/blob/v4.1.1/scss/bootstrap-material-design.scss):

```
// IMPORTANT: For use of source and variable overrides, import the following file directly, *NOT* this one.
//  This file primarily exists to create the static css distribution.
@import "core";

$theme-colors: map-merge((
 primary: $blue-300/*,
 success: $green,
 info: $light-blue,
 warning: $deep-orange,
 danger: $red,
 light: $grey-100,
 dark: $grey-800*/
), $theme-colors);
```

And then built just the CSS:

```
$ npm run build:css
$ npm run build:css-min
```

Am I doing something wrong? Any help would be really appreciated. Thank you!

**Comment by vinyanalista** [comment]
Since I'm editing the source code anyways, I decided to edit the file [_variables.scss](https://github.com/FezVrasta/bootstrap-material-design/blob/v4.1.1/scss/_variables.scss) directly.

Line 25:

```
  primary: $teal,
```

I switched to:

```
  primary: $blue-300,
```

This time it worked.

For what I need now, that is enough. If you have better ideas, please share.
