### ISSUE TITLE
drawer background

### ISSUE THREAD

**Issue by yuraantonov11** [mdbootstrap/mdb-ui-kit#1267]
#### Summary
in styles installed by npm i cannot find  in .bmd-layout-drawer class background color and drawer is transparent

#### Expected result
.bmd-layout-drawer class must have background color white

**Comment by bretonio** [comment]
I have this difficulty as well. Because the push version of the fixed left menu is not pushing the main body past the right margin on a small screen, I am thinking need to use an overlay on medium and down.  `bmd-drawer-overlay-md-down` ...

On the small screen this renders as a dimmed, transparent slide-out drawer matching the main content. But clicking outside it hides it normally. And on  medium and up the push action works fine.

The obvious hack attack is as follows (in Jade-Pug)

```
#dw-s1.bmd-layout-drawer.bg-faded(style='background-color: white;')
```

And bazinga! Any colored drawers you like. Thanks for raising this it made me open up the SCSS file and think &mdash; although the answer was much simpler than that. Occam's Razor simple.
