### ISSUE TITLE
Missing DOM elements in popovers with dynaically generated HTML content

### ISSUE THREAD

**Issue by wol-soft** [mdbootstrap/mdb-ui-kit#1371]
#### Test Case
https://codepen.io/anon/pen/OeeOmy

#### Summary
If I render the content for a popover dynamically some elements disappear after upgrading from version 4.1.1 to version 4.1.2 (eg. tables and svg). To reproduce click on the red square in the codepen,

#### Expected result
Expecting elements to be present in the DOM

**Comment by Valronn** [comment]
You must provide function as an attribute. And after that, return needed content.
`$('.test').popover({
  content: () => function () { /* Your content here... */}`

**Code pen**
https://codepen.io/anon/pen/rXavKp

**Comment by wol-soft** [comment]
Hi @Valronn,

hmm your solution fixes the issue but now we have a function returning a function returning the content. A simple function returning the content for the popover doesn't work (which works with version 4.1.1 and should work according to the documentation. The documentation just says provide a function and nothing about a function returning another function).

Using the double nested function feels like a workaround and just plain wrong to me. 

Edit: and it's still very confusing some elements are present if using a simple function while some other elements are missing.

**Comment by Valronn** [comment]
My bad. I thought you needed a fast solution.

So, the reason for not displaying some content is because it's being sanitized. In short, you must allow elements(such as: table, td, tr, thead, tbody etc...) in popover's whitelist. 

I'm not very good in jQuery, but I found  solutions on stack overflow.
[https://stackoverflow.com/questions/55362609/bootstrap-4-3-1-popover-does-not-display-table-inside-popover-content](url)

Also, there is good explanation in the bootstrap documentation about sanitizer in Tooltips and Popovers [https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer](url)

I hope that will help you.

**Comment by FezVrasta** [comment]
I'd say it's more of a Bootstrap issue, I'll close here

**Comment by wol-soft** [comment]
Thanks @Valronn for the clarification. I've set up an extended whitelist now to support the elements I use with a simple function.

Good to know a nested function breaks the sanitizer. Can't imagine that's an intended behaviour. It's also possible to nest the functions even deeper:

```js
$('.test').popover({ content: () => () => () => ....... () => () => { /* Your content here... */}
```
