### ISSUE TITLE
Tooltips don't work when nested in a Label element

### ISSUE THREAD

**Issue by Okomikeruko** [mdbootstrap/mdb-ui-kit#1375]
#### Test Case
https://codepen.io/anon/pen/OKWGpP

#### Summary
Tooltips do not work if the element is nested in a `<label>` element. They do work when not nested but managing spacing is difficult. 

#### Expected result
I want a help icon next to the label for a form field to help explain what goes in that field without taking too much space. It's difficult to manage spacing when it's not nested in

#### Additional Information
It is difficult to manage spacing an element not nested within the `<label>` element since labels are automatically assigned the `.bmd-form-label` className, for which the CSS sets the position to 'absolute'.

**Comment by Valronn** [comment]
Hello.

Your table element isn't displaying because tooltip sanitizes it. You can learn more about [here](https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizerl).

So the solution to your issue is [here](https://codepen.io/anon/pen/ymgmWv).

Also, nested functions fix the problem too, you can try use them, if you don't want always predefine `<table>, <tr>, <td>` etc...

**Comment by Valronn** [comment]
Hello.

Try this solution [here](https://codepen.io/anon/pen/LwWPXZ)

**Comment by FezVrasta** [comment]
Thanks for the help @Valronn!
