### ISSUE TITLE
battery icons don't seem right

### ISSUE THREAD

**Issue by tomByrer** [mdbootstrap/mdb-ui-kit#141]
They look all full; intentional?

Thanks for all your excellent work!

**Comment by FezVrasta** [comment]
Yup it's a problem I'm aware of... Limitation of the font generator I think

**Comment by tomByrer** [comment]
I had a feeling you knew, but now I know you know I know ;)
What font generator did you use please?

**Comment by FezVrasta** [comment]
Moonicon is its name I think

**Comment by FezVrasta** [comment]
Can't find a way to use opacity levels on font icons... if someone has a solution please share it.

**Comment by ghost** [comment]
I don't have a solution for opacity, but I have a short-term solution for you @tomByrer .

Located in Google's official [material-design-icons repo](https://github.com/google/material-design-icons), there's a set of [CSS Sprites](https://github.com/google/material-design-icons/tree/master/sprites/css-sprite) and [SVG Sprites](https://github.com/google/material-design-icons/tree/master/sprites/svg-sprite). The battery images are located within {type}-sprite-device.{png,svg} respectively along with their corresponding stylesheets.

@FezVrasta - Would you be open to a PR incorporating either the official Google CSS or SVG sprites for the material design icons rather than the compiled font set currently provided by IcoMoon?

**Comment by FezVrasta** [comment]
@francismakes I think would be useful :)

**Comment by GradyD** [comment]
It looks like google fonts are now included in this project. It looks like this happened back on commit #128.

Can this be closed?

**Comment by FezVrasta** [comment]
@GradyD no, the current implementation is just a porting of the SVG official icons. The bug is still there.

I'm waiting the official Google iconic font to replace the current one.

**Comment by FezVrasta** [comment]
fixed wih #452
