### ISSUE TITLE
doesn't work with bootstrap 5.3 dark mode

### ISSUE THREAD

**Issue by allanchao** [mdbootstrap/mdb-ui-kit#1507]
Just want to raise the issue in case no one has noticed, but I believe mdb 6.1.0 does not work with bootstrap 5.3.0-alpha1 dark mode. Seems like mdb is overriding the color scheme to stay in light mode, even if dark mode is set.

https://getbootstrap.com/docs/5.3/customize/color-modes/

**Comment by gbujanski** [comment]
MDB has integrated BS and you don't need to add it separately. Adding BS separately will duplicate some code and may cause problems. Whenever a new BS version comes out, we plan to update the MDB to the latest BS version.

Please note that BS 5.3.0-alpha1 as the version name suggests is in the alpha stage. That means everything can still change. In subsequent versions, the solutions introduced in the alpha1 version may be changed/improved or they can opt out of this solution. 

That's why we haven't updated BS at the moment. When BS 5.3.0 comes out in a stable version, we will update the MDB to the latest BS version. Until then, we are tracking changes and checking what we can potentially do to make the new BS version work in the MDB.
