### ISSUE TITLE
The btn-default is not very visible and looks like a link

### ISSUE THREAD

**Issue by lipis** [mdbootstrap/mdb-ui-kit#151]
Maybe it shouldn't have transparent background as it's not really clear if it's a button or not
http://jsbin.com/bufavapoji/1/edit?html,output

**Comment by FezVrasta** [comment]
This is how the default button looks on material design, maybe I can tweak it a bit

**Comment by lipis** [comment]
Weird.. sometimes they are visible white sometimes not..
http://www.google.com/design/spec/components/buttons.html dunno

**Comment by lipis** [comment]
OK it depends on where they are in the content.. maybe for the default there should be a `btn-raised` so people could use that whenever possible and the default would be flat.. or the vice versa..

**Comment by lipis** [comment]
After a second thought.. I think the default should be the raised one and `btn-flat` if you want to have it transparent..

**Comment by FezVrasta** [comment]
I've double checked the documentation, buttons in MD have not a "default" style, they are styled second the importance of them and the purpose. So I don't think it's wrong to give the less important style to the default one and let the user add importance to it using the classes provided.

**Comment by waleedq** [comment]
I think the btn-raised should be the default one, as most of the site buttons should be raised by default, and less buttons are flat.

This is what the MD guide lines recommend as you can read in this section 
https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

"Raised buttons add dimension to mostly flat layouts. They emphasize functions on busy or wide spaces."

So as most of the modern layouts are flat layouts then raised buttons are needed the most.

also "Use raised buttons to give more prominence to actions in layouts with a lot of varying content."

as for the flat buttons they suggest to use them in a layered design such as a dialog, toolbar or a card inside the page.

"Use flat buttons for toolbars and dialogs to avoid excessive layering."

Thank You.

**Comment by lipis** [comment]
:100:

**Comment by FezVrasta** [comment]
When you watch most of the material design apps, the most used buttons are the flat ones. I wouldn't like to have the raised buttons as default honestly

**Comment by rosskevin** [comment]
The spec states:

> Never use raised buttons within persistent button areas.

and

> Use raised buttons to give more prominence to actions in layouts with a lot of varying content.

and provides multiple examples, many of which are flat buttons.

In addition, flat buttons are basic, and raised adds decoration.  Instead of writing the code to raise then overriding to remove, raised buttons are built upon and enhance flat buttons.

My interpretation of the spec: "Use raised buttons to call attention".  To me this means "Add btn-raised in the cases where you want to call attention."

As @FezVrasta says, this is the Material Design way, and is the same in google's own MDL.

You could easily make your own default by changing your templated markup or adding some simple js like `$('.btn:not(.btn-flat)').addClass('btn-raised')` (untested code, wherein the `btn-flat` is just a marker that has no styles)

**Comment by waleedq** [comment]
As you can read in the layout guide lines 

Choosing a button style depends on the primacy of the button, the number of containers on screen, and the screen layout.

"Choose raised or flat depending on the container it will be in and how many z-space layers you have on screen. There should not be many layers of objects on the screen."

and

"Use primarily one type of button per container. Only mix button types when you have a good reason to, such as emphasizing an important function."

Maybe we should define the default state by adding a class to the container, this would make it easier to flip between the 2 states.

@rosskevin 
My interpretation of the spec: "Use raised buttons to call attention". To me this means "Add btn-raised in the cases where you want to call attention."

This is not what they mean with that, in the case of a content website buttons can't be flat as they will be hidden between the content this is what they mean by attention, and again as you can read in the "Flat & raised buttons" section 

"Raised buttons add dimension to mostly flat layouts. They emphasize functions on busy or wide spaces."

buy flat layouts we mean a single layer layout, something like this page which have a lot of white areas or (single color areas), you can use flat buttons here, it makes no sense to use flat buttons as they will look like links for the user.

have a look at the Do, Don't example where they show you the buttons in the settings page, flat buttons can't be used as normal actions buttons, flat buttons should be used with a 2nd layer of content where the focus is on the content not the actions.

Thank you.

**Comment by rosskevin** [comment]
I understand your position and debated both myself.  I actually defaulted to raised in my initial refactoring, but found it to be much more code and different than MDL for example.  

I do not agree that the spec espouses raised by default. It makes no mention of a default state.  

Here's an analog: Try an experiment with your loved one.  Every time you exit your home/vehicle, turn the radio up to 100%, because you can always turn it down to the level you want, right?  What do you think your loved on will do?  Probably jump out of their seat the moment they turn it on, and every other time!

If "This is not what they mean with that", why does MDL default to flat first as well?

I would pose that it's because raised "emphasizes", which means it "stands out".  This means that it should stand out in your markup as well.  Not "always stand out" (default the volume to 100%) and add  something to de-emphasize (turn the volume to a comfortable level).  

Markup written in this fashion would be the inverse of emphasis.   For example, the following is how it is now.  Which markup stands out in the following?

``` html
<button class="btn">foo</button>
<button class="btn">foo</button>
<button class="btn btn-raised">foo</button>
<button class="btn">foo</button>
<button class="btn">foo</button>
```

Before we had three states:
1. none - undefined regarding MD - this ended up being a bootstrap raised btn
2. `btn-raised`
3. `btn-flat`

I made these refactorings:
1. I removed 1 which was undefined regarding material.
2. I removed btn-flat, which is unnecessary as it is the base from which we build.
3. I refactored/reduced the code for `btn-raised`.

If you were using the default `btn` without `btn-raised` before, you were in an undefined area that was actually (_mostly_) BS styled, not material design. 

So to use MDB, you either a) do nothing which is flat, or b) add `btn-raised`.  
1. This is _very easy_ to comprehend and create markup.  
2. This change is a net-loss of code (both in this library and for the user).  
3. This change makes us more similar and less different to MDL, which I think is a very good thing since some users will want to switch to MDB from MDL once they start wanting some of the more powerful things that bootstrap provides.

To add something like a container level btn-raised type, we would then have to maintain a set of styles to reverse the styles to obtain a flat btn.  This is more code, not less; more code to maintain and harder to comprehend for maintainers and users.  

In the end, if you weren't using `btn-raised` before, you were (_mostly_) using bootstrap defaults.  `btn-raised` is not a lot to add, is net-less code, and provides consistent results.  While I understand the desire to flip the default the other direction, I firmly believe the reasons above make this the right decision.

**Comment by FezVrasta** [comment]
On a private implementation of MD I've written for the company I work for, I've not a default state, there are `-flat` and `-raised` classes, and both have the same importance, every time someone needs a button he have do decide which one he wants
