### ISSUE TITLE
Consider non-copy-left license

### ISSUE THREAD

**Issue by matt-cook** [mdbootstrap/mdb-ui-kit#201]
Would you consider a more permissive license such as MIT/BSD? I'm not personally interested in a commercial use, but am planning on building my personal site with only more truly free code.. would love to use this as a starting point.

Bootstrap is licensed under MIT, so it would be great to see this library under the same license (rather than making it more restrictive with GPL): http://getbootstrap.com/getting-started/#license-faqs

**Comment by FezVrasta** [comment]
This license was chosen because I wanna help for free people that are willing to use this theme for no profit projects, but I even need some money to continue the development of
 this theme, so people that wanna make money with this theme have to fulfill my conditions.

I don't think I'll change the license.
