### ISSUE TITLE
Fonts are wrong in mobile (Android, Chrome)

### ISSUE THREAD

**Issue by ppeccin** [mdbootstrap/mdb-ui-kit#260]
I know that mobile platform is not really supported yet, but I'm testing it and its working pretty fine.
But even in Android 4.4 the fonts are being rendered as "OTS derived", not native Roboto.

This is caused by the rule:

font-family: RobotoDraft, Roboto, 'Helvetica Neue', ...

The "RobotoDraft" as the first option is causing the browser to not use Roboto directly.

Instead, why not specify this rule as:

font-family: Roboto, RobotoDraft, 'Helvetica Neue'....  ?

That way it should work better in platforms that offer the Roboto font natively, right?

I would suggest that even the font face name "RobotoDraft" should be renamed to something more specific to this project, like "BootstrapMaterialRoboto" or something. That, together with the font-family inversion above would make it pretty clear that the Browser should use "Roboto" if already available, and then BootstrapMaterialRoboto if not.

That or maybe modifying the @font-face rules to include local('Roboto') as a first option, to make mobile browsers use the native font whenever possible.

Thanks,

**Comment by FezVrasta** [comment]
Good point, I'll see what's the best practice

**Comment by FezVrasta** [comment]
There's a problem with this request.

I provide RobotoDraft and not Roboto because RobotoDraft is the new version of Roboto used in Lollipop.

It's quite different from the old Roboto font (the one you can find on 4.4 or below). The real problem is that, having the same name on Lollipop (Roboto on lollipop is the new one aka RobotoDraft), it will load from web fonts even when it's available on the system...

The options are:

Load Roboto, don't care if is the old one or the new one.
Continue with the current method.

I think the first is the best approach so I'm going with it for now.

**Comment by ppeccin** [comment]
I see...

Do you know why I'm getting different behavior in Chome in Windows vs Chome in Android?
In Widows, the browser is rendering your specified font correctly, RobotoDraft.
But in Android, its not using neither RobotoDraft nor the native Roboto. It shows as OTS Derived.

Any idea?

**Comment by FezVrasta** [comment]
No idea, by the way I've set "Roboto" local as first choice in the master

**Comment by ppeccin** [comment]
Nice, I will try it.

Thanks!

**Comment by FezVrasta** [comment]
you're welcome
