### ISSUE TITLE
Button active class

### ISSUE THREAD

**Issue by braginteractive** [mdbootstrap/mdb-ui-kit#269]
Thoughts on adding an active class to the buttons? I am thinking it would be the same styles as hover/pressed.

So for the normal buttons it would be:

```
<button class="btn btn-primary active">Button</button> 
```

```
.btn:not(.btn-link):not(.btn-flat).active {
    box-shadow: 0 6px 10px rgba(0,0,0,.23),0 10px 30px rgba(0,0,0,.19);
}
```

**Comment by FezVrasta** [comment]
Nice idea

**Comment by ianserlin** [comment]
While we're at it for a refactor of hover/active, the undocumented issue of having to write "btn btn-" as literally the first characters of your class attribute to get the desired hover behavior is brittle and confusing.

I'm specifically talking about the following lines in _buttons.less:

```
// This is needed to style buttons which has not a variation suffix (they must be stiled as btn-default)
.btn-link, .btn:not([class^="btn btn-"]), .btn-default {
  color: @lightbg-text;
  &:hover {
    color: @lightbg-text;
  }
}
.btn:not([class^="btn btn-"]), .btn-default, .btn-flat:not(.btn-link) {
  &:hover, &.active {
    background-color: rgba(255,255,255,0.5);
  }
}
```

So if I happen to do:

```
<button class="invite-button btn btn-primary">Invite</button>
```

It's hover state will be transparent instead of my primary color.

I suggest using

```
[attr*=value]
Represents an element with an attribute name of attr and whose value contains at least one occurrence of string "value" as substring.
```

instead.

**Comment by FezVrasta** [comment]
Thanks I'll probably patch it tomorrow, I had used the ^= selector because it was used in the original bootstrap or maybe in some bootswatch I've looked at

**Comment by ianserlin** [comment]
PR submitted to save you some time. Cheers!

**Comment by GradyD** [comment]
Can this be closed now?

**Comment by assistcontrol** [comment]
No, the underlying issue here is still present. The ability to make a button have the depressed looked when it has the "active" class is really important for those of us with button-heavy forms.

See http://jsfiddle.net/r6drg84n/ for example. That's bootstrap's radio button thing (http://getbootstrap.com/javascript/#buttons-checkbox-radio).

See http://jsfiddle.net/h9zao0jb/ for the same HTML but using bootstrap-material-design. Because b-m-d doesn't honour the "active" class, all the buttons look the same and there's no way to tell which is selected.

**Comment by FezVrasta** [comment]
This is an issue but you should not use buttons in this way if you want to follow material design.

**Comment by FezVrasta** [comment]
implemented

**Comment by hiteshgpt** [comment]
@FezVrasta 
I downloaded the latest "dist" from the below link and using it. Everything else seems to work fine, except some issues.  Like active button state (as mentioned in this thread) and inline radio buttons etc. Looking at the history, looks like these issues are already fixed. Why can't I see them? Am I using an older version

https://github.com/FezVrasta/bootstrap-material-design/tree/master/dist
