### ISSUE TITLE
Dropdown point of origin - material should appear from touchpoint.

### ISSUE THREAD

**Issue by jtolla** [mdbootstrap/mdb-ui-kit#280]
http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-material-response

"When new material is generated as a result of direct user interaction, surface growth motion should originate from the point of input."

**Comment by FezVrasta** [comment]
Actually the Dropdown.js supports something like this, It could be improved.

**Comment by rcollette** [comment]
The point of input is not the same as the touchpoint.   The material should essentially cover the related input.  So origin point for material growth should be one of the four input corners to expand across the input (ex. top-left origin = grow down-right, bottom-right origin = grow top-left)

**Comment by caseahr** [comment]
I don't agree with this in the context of dropdowns, in the classic bootstrap sense.  The point of origin example depicts a menu being launch from a button.  That is not a dropdown.  A better example to emulate for dropdowns is located on [this page under the Edit Shipping Info example](http://www.google.com/design/spec/components/menus.html#menus-usage).  It will still take a little doing to implement.

**Comment by jtolla** [comment]
@rcollette I would disagree that "the point of input is not the same as the touchpoint". I think that's exactly what it is in the context of this statement.

@caseahr The "cascading dropdown" video is a close example of what I'm suggesting.

**Comment by rcollette** [comment]
@caseahr I agree the movie that depicts the state "drop down" for the edit shipping example is the way it should be.  My memory of the documentation was not accurate.  I recalled the spec saying that the  selected field should be overlayed but didn't recall it being as complex as the video shows.  Sorry for my confusion.

**Comment by FezVrasta** [comment]
So, we are talking about this behavior:

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNb3hiNjFBTUU4V0k/components-menus-menus-appbar_dropdown_spec_large_xhdpi.webm

**Comment by caseahr** [comment]
In my opinion, this might need to be a new issue.  The title of this issue is "material should appear from touchpoint," but I don't believe that to be true.  The current example on [the demo page](http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu) shows the dropdown options appearing from the left and growing to the right.  This is not the desired animation.  The end state however is perfect.  It should just animate differently as seen [here on a different material design framework site.](http://material-ui.com/#/components/dropdown-menu)

To answer your question @FezVrasta, no I think the behavior shown there is more akin to the bootstrap navbar elements which you already have working well on your bootstrap elements page.  The only thing missing there is the animation.  So basically, you just need a little animation work.  No biggie, right?  I would like to help... but I've never done the whole pull-request and everything before.  perhaps I should give it a try.

**Comment by FezVrasta** [comment]
everything is automated by Grunt, you have just to edit the LESS files and run grunt material:less to compile CSS :)
