### ISSUE TITLE
TravisCI fails

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#313]
The TravisCI test fails with:

```
Writing location.js file
PhantomJS is already installed at /usr/local/phantomjs/bin/phantomjs.
npm ERR! phantomjs@1.9.7-7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-7 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab090.5
npm ERR! command "/home/travis/.nvm/v0.10.34/bin/node" "/home/travis/.nvm/v0.10.34/bin/npm" "install"
npm ERR! cwd /home/travis/build/FezVrasta/bootstrap-material-design
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Doesn't look like a problem with the source code or with the test but something about TravisCI... Anyone has some suggestion?

@dandv are you the last one who edited these files? I'm not sure.

**Comment by dandv** [comment]
Might be caused by [installing spacejam](https://github.com/FezVrasta/bootstrap-material-design/blob/master/.travis.yml#L12), which depends on phantomjs. Let me look.

But as you can see, [build have passed just fine after my Meteor PR](https://github.com/FezVrasta/bootstrap-material-design/pulls?q=is%3Apr+is%3Aclosed). up to and including PR #295.

**Comment by dandv** [comment]
Not a Meteor problem, we can remove the label. It's caused by the phantomjs installer, which is caused by the new [upstream Node.js v0.10.34 certificates issue](https://github.com/joyent/node/issues/8894).

If you need this fixed ASAP, we can change https://github.com/FezVrasta/bootstrap-material-design/blob/master/.travis.yml#L3 to `0.10.33`.

**Comment by FezVrasta** [comment]
Thanks!
