### ISSUE TITLE
.modal-backdrop is not working

### ISSUE THREAD

**Issue by NenadKaevik** [mdbootstrap/mdb-ui-kit#318]
When i put the modal backdrop class it darkens and transparents the whole body including the opened modal.

**Comment by FezVrasta** [comment]
please provide a codepen, use the pen provided in CONTRIBUTING.md as base. Thanks!

**Comment by kylerberry** [comment]
@FezVrasta http://codepen.io/kylerberry/pen/gbrxGG It looks like the modal is `display:none` by default. The animation classes don't add the `display:block` back in. Also, the modal shouldn't require the animation classes to show.

**Comment by GradyD** [comment]
Is this still valid? I looked at the codepen and everything looks right.

**Comment by GradyD** [comment]
@FezVrasta can you provide any insight on this? If this is still an issue I will fix it with all of my other modal updates... just not sure what the issue is.

**Comment by FezVrasta** [comment]
I'll look into this asap

**Comment by miri-am** [comment]
For me it works again if setting the z-index: 

```

.modal-backdrop {
  z-index: 999; // was 1040
}
```

**Comment by Zhigalin** [comment]
@FezVrasta 
You are using bootstrap 3.3.2 here: http://fezvrasta.github.io/bootstrap-material-design/#dialog 
But if you try to upgrade to 3.3.5 you will see this issue appear.
I don't know why, but someone has just added z-index: 1040; to .modal-backdrop in bootstrap 3.3.5

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).

**Comment by Zhigalin** [comment]
@rosskevin 
Hi. The issue is still there.

**Comment by rosskevin** [comment]
I altered the codepen provided and removed any remnants of bootstrap-material-design.  [You can view it here](http://codepen.io/rosskevin/pen/NGJmyZ).  If I'm reading the issue correctly, my codepen shows that this has nothing to do with bootstrap-material-design, as it looks exactly the same with or without bmd.

Perhaps submit a codepen that works with bootstrap first, then a fork with bootstrap-material-design.

**Comment by Zhigalin** [comment]
@rosskevin 
You aren't reading the issue correctly. I only have my tablet ATM, so I cannot provide any examples.
This issue is with animated, hidden by default modal, which is being covered by .modal-backdrop so that:
1: The modal is darkened like the rest of the page.
2: You cannot click inside the modal.

**Comment by rosskevin** [comment]
Ok,  so it would be most helpful to see a working codepen that is bs3 only,  then a codepen with bmd added so we can hunt this down.

**Comment by Zhigalin** [comment]
@rosskevin
Use bs3.3.5, bs3.3.2 is OK.

**Comment by rosskevin** [comment]
@Zhigalin - I don't understand what you are trying to tell me with your last comment.

There are quite a few related issues with modals in the bootstrap issues list, and most are related to improper use of them.  One such recommendation from the bootstrap team is to make sure and place modals at the bottom of the body, otherwise the z-index is incorrect and the backdrop covers it.

Until we have a codepen that demonstrates the problem, I'm going to close this because we cannot take action on something we cannot reproduce.  I'm not definitively saying it is not a problem, I just cannot help without the test case.

If this is still an issue, please provide the requested codepen test cases and reopen.
