### ISSUE TITLE
.map files are missing on CDNJS.com

### ISSUE THREAD

**Issue by h6ah4i** [mdbootstrap/mdb-ui-kit#342]
I noticed that .map files are missing on [CDNJS.com](https://cdnjs.com/libraries/bootstrap-material-design). Please add .map files as same as [JSDelivr.com](http://www.jsdelivr.com/#!bootstrap.material-design).

**Comment by FezVrasta** [comment]
I can't remember how I had inserted it to CDNJS... probably someone else did it for me. Have someone idea about how to proceed?

**Comment by andrewjli** [comment]
You need to submit a pull request with the relevant files to the [cdnjs repository](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/bootstrap-material-design)

edit:
Actually, looks like they're switching to using an automatic updating system, but their auto-update config does not include the .map files, so that will need to be updated instead.

**Comment by FezVrasta** [comment]
I have to clone locally the entire repository? emh nice... ok I'm cloning it.. will take some time

**Comment by andrewjli** [comment]
Well, you could just create an issue on the repo, I guess?

**Comment by FezVrasta** [comment]
I could just provide jsdelivr :\ is much more easier use it...

https://github.com/cdnjs/cdnjs/issues/4177
Use this issue to track the problem. Closing this one now.

**Comment by FezVrasta** [comment]
ok should be fixed thanks to @PeterDaveHello

**Comment by PeterDaveHello** [comment]
No problem.
