### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by unsafecode** [mdbootstrap/mdb-ui-kit#410]
Will it be possible to adopt a standard license in the future?

**Comment by FezVrasta** [comment]
Yes I'm working to move to AGPLv3 in the near future

**Comment by kmmbvnr** [comment]
What about commercial licence? Will it be present?

Actually AGPLv3 for CSS seems not requires to open non CSS staff. Isn't it?

**Comment by FezVrasta** [comment]
requires that every project that uses agpl must use agpl as well.

There will be a commercial license as well.

**Comment by kmmbvnr** [comment]
Nope, AGPL is only for derived work. If someone takes BSD css framework, mixes them with AGPL, the original framework code not  became AGPL licenced. Only the glue code became AGPLed.

So at most AGPL could make project html/derived js/derived css  AGPLed, but the backend, and most of non directly related to material design js code could be licenced differently. But, anyway, even this could be good point to buy commercial licence for most customers.

**Comment by FezVrasta** [comment]
Honestly everything I've read about AGPL is that if you use licensed software inside yours, you have to move everything to AGPL and you must distribute source code to every user which uses your website or software (this is the purpose of the AGPL).

By the way I'm contacting a lawyer to be sure of how to proceed.

**Comment by rmhrisk** [comment]
Please consider using a more friendly license than AGPL; this looks like it will be a great project it would be a shame for it not to be usable by people because of licensing terms.

**Comment by 0x0ece** [comment]
+1 for using something friendly, i.e. MIT like Bootstrap. I understand the desire to get some money out of the hard work and I respect that, yet I think that being 1st result in Google for "bootstrap material design" is priceless. Without a good license, another project will eventually take off.

Just for reference, for a side project I'm using react-material-ui (http://material-ui.com), instead of react-bootstrap + this theme. I don't particularly like that project better, I've just chosen it for the license.

**Comment by unsafecode** [comment]
+1 for licensing too.

@ecesena I also have considered that one for the same reason, yet still we don't leverage on React, and we had better to rely on a pure UI framework like this.

**Comment by kmmbvnr** [comment]
Guys, I think making +1 comments is not a good way to ask about friendly licence.  Author of this project have gratipay account https://gratipay.com/FezVrasta/ If you are so happy with bootstrap-material, why just not to give a bit of thank you to the author?

**Comment by unsafecode** [comment]
@kmmbvnr Thanks for sharing, I was wondering about this options.

The licence issue, however, is intended not to ask for "free" product, but for policy and compliance reasons.

**Comment by rmhrisk** [comment]
Yes, this isnt about free; people should get paid for their work and donations is a very small way to contribute but many don't realize that by using GPL licenses they exclude many from being able to even touch it.

**Comment by lukebranch** [comment]
@FezVrasta ,

Here's another open-source project that is migrating over to a more suitable license for their product:

https://www.odoo.com/blog/odoo-news-5/post/adapting-our-open-source-license-245?utm_content=buffere8c98&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer

I thought it may be of some interest given your situation.

**Comment by chaturadilan** [comment]
Since this is kind of a library project, it is good to release this under MIT or BSD. If you do so your project get more popular.

**Comment by versedi** [comment]
I agree with chaturadilan – and analogically – more popular, than more donations on gratipay.

**Comment by ashwoods** [comment]
First, I am not a lawyer.... 

Sadly the licensing _mess_ on this project has forced us to stay away it for now. Besides all the ethical implications of trying to commercialise the work of others, there are three practical problems that are very messy: 

a) the choice of the license: it is normally not advisable to come up with a non-standard license. licenses are hard, and can create many headaches if done right. What is for example a no-profit project? That means I can make a project that is no-profit ( practically a fork ) and use that however I want (I could be a for-profit entity using no-profit projects). That is just one example I found and IANAL.

b) my understanding is that the GPL and AGPL apply to derivate works. it hardly can be argued that any web project is a derivate work of a css theme, specially if the project can work well as is with a vanilla bootstrap style and by the cascading nature of CSS. So moving to agpl isn't going to solve anything. 

c) I see several pull requests, but I do not see any signed Contributor License Agreements nor transfer agreements. If that's the case, the current code might not belong exclusively to Fernando, as pull requests do not imply a copyright transfer/agreement, no matter what you put on that license (afaik it has to be explicit). That means that at this moment, Fernando might not even have the rights to license the current project commercially. But that's a complicated grey zone entirely. http://programmers.stackexchange.com/questions/191535/could-submitting-a-pull-request-ever-constitute-accepting-a-contributor-licence

**Comment by FezVrasta** [comment]
There is a contributing agreement. And I'm Federico, lol

**Comment by ashwoods** [comment]
Sorry federico. :D Don't know where the fernando came from. Happens when trying to write a comment when trying to code at the same time. Adding terms to the source might not be enough. Depending on the jurisdiction, copyright transfers have to be explicit. You have to have CLA's. Actually, signed CLA's. It get's even murkier when you are dual licensing, and/or with non standard licences. 

http://jacobian.org/writing/contributor-license-agreements/
http://www.groklaw.net/article.php?story=20110524120303815

The problem is the risk. Without transparent and/or standard licensing, and no CLA's, it's simply not worth it for any serious company or for anyone who wants to contribute.

**Comment by FezVrasta** [comment]
Yes that's why I want to move to a standard license, lol.

But the last lawyer I've contacted asked me 1000 and more euro to give me some info so I'm not so inclined to pay one right now :/

**Comment by Calinou** [comment]
Selling the work of others, provided you don't exploit it, is not unethical.

http://freedomdefined.org/Licenses/NC

So, please switch to a free license. Thanks in advance.

Note that the GPL, LGPL and AGPL **do** allow commercial use. They are however copyleft licenses, just like CC BY-SA is.

**Comment by jfmcbrayer** [comment]
I support the move to AGPL. A BSD or MIT style license would be more friendly for some projects, but any move to any standard license that is not NC would be a huge improvement. I am working on an AGPL web application, and would like to use this, but cannot if I plan to provide a commercial hosted solution for my Free app.

**Comment by jmls** [comment]
I would certainly prefer a bsd/mit licence, same reasons as ecesena. We can't use this library as much as we would like to

**Comment by daviddeutsch** [comment]
http://choosealicense.com/

Just a note here: The fact that you use a custom license doesn't just make it near-impossible for commercial projects to use your code, it's the same for FOSS projects.

Using the AGPL is nonsensical because the only difference between GPL and AGPL is that the AGPL requires you to make the source code available to users of a website or -service. Making the JS and CSS source available to users is kind of what webservers do by default. It may be argueable to what extent you restrict the use of pre-processing, but that's easy to get around, too.

Finally - I would be very, very careful to use a restrictive license like GPL (which I'm a HUGE, HUGE fan of and use all the time) simply because your library is mostly derivative work - you are implementing a public design document from Google in an MIT licensed CSS framework from Twitter.

It would probably be up to a court to decide what standing you have in this matter, but my gut feeling is that you should go with using the least restrictive option (MIT, like Twitter) otherwise you give the other parties all the leverage in the world to attack you shold they feel like it.

TL;DR: I would suggest that the most logical course of action would be to go with MIT.

**Comment by Calinou** [comment]
> Making the JS and CSS source available to users is kind of what webservers do by default

These days, people often distribute minified JS and CSS without distributing the unminified source. Obfusated code is not source code.

Usually, you want to pick the same license as the source project (which is Bootstrap here).

**Comment by daviddeutsch** [comment]
@Calinou

> These days, people often distribute minified JS and CSS without distributing the unminified source. Obfusated code is not source code.

Yeah, that's what I was trying to say with

> It may be argueable to what extent you restrict the use of pre-processing, but that's easy to get around, too.

You'd still get around it if you simply deliver material-bootstrap to the browser separately, making the difference between GPL and AGPL irrelevant.

**Comment by Denoder** [comment]
and now throughout this long conversation i is confused. What is the take on this? is it free? Is it not?

**Comment by FezVrasta** [comment]
If you'll earn money from the project which uses this theme, than it's not free. Otherwise, it's free

**Comment by Calinou** [comment]
> and now throughout this long conversation i is confused. What is the take on this? is it free? Is it not?

It's not [free/libre software](https://gnu.org/philosophy/free-sw.html) because it doesn't respect the four freedoms:

> - The freedom to run the program as you wish, for any purpose (freedom 0).
> - The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
> - The freedom to redistribute copies so you can help your neighbor (freedom 2).
> - The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

**Comment by FezVrasta** [comment]
It's free like beer, not like speech

**Comment by daviddeutsch** [comment]
@FezVrasta Yes. That's why it's impossible to use - even for FOSS projects. Seriously: People who understand software licensing wouldn't touch this with a ten foot pole, your custom license is a _huge_ red flag. There is a reason why the GPL (taunted, falsely, by a lot of people as anti-business or even "viral") makes no restrictions on commercial use and you can find quotes by Stallman speaking out explicitly against making such restrictions.

You're hurting all sides here while standing on _extremely_ flimsy ground (as mentioned before: your work is largely an adaptation of less restrictive - bootstrap - or not restrictive at all - material design - projects). I don't see how you could reasonably justify a commercial interest. Continuing to, at the same time, hurt non-commercial use leaves you with little sympathy from any side.

**Comment by Denoder** [comment]
yea i no longer have interest in this project then <_<. Sure, I'm okay with commercial licenses, however I wouldn't have the immediate funds for it so contributing when I cant even use it yet wouldn't make sense for me.

Like you have the source code on Github so at first glance people will think that's it's free (few other dev friends of my thought so too), then I went ahead and looked at the licensing issues and it's a real turn of for us. Initially this would have been fine if it was like a pay first, then access to a private repository of it cause that would have made sense for me at least, plus its on cdnjs and jsDeliver. So who knows whover else might have grabbed this thing unwillingly without noticing the licensing effects. :/ - You really should clean this up man.

**Comment by MarshallOfSound** [comment]
Personally I originally found this on `cdnjs.com` then google searched it and found the demos.  That process flow (which I am sure many others have followed aswell) didn't even lead me to a Github repo let alone any terms of licensing.

It looked perfectly free and open source for anyone to use, now I am not touching this with a 10 foot pole because I am not sure if you or anyone else has any legitimate claim to the source code that is in this repo.

The afore mentioned concerns that you don't have a legitimate claim to other peoples pull requests into this repository is a massive issue that needs to be resolved properly and quickly

**Comment by meetbryce** [comment]
Unfortunately, I have to agree with the majority of people here, if it's not available under MIT or BSD I won't be using this project longer than I absolutely have to.

If I had more time, I'd probably spend the time to create a version myself and may well do that when the next version of Bootstrap is released.

**Comment by jofftiquez** [comment]
This project is one of the best I say. I want to use it but nah. The license, if you could make it MIT that would be great.

**Comment by jofftiquez** [comment]
@MarshallOfSound Exactly!

**Comment by FezVrasta** [comment]
I'm considering the MIT.. I have not enough time to follow this project anymore and probably open sourcing it will give it a new life.

**Comment by meetbryce** [comment]
Would be great to see that happen! I think your work will have a lot more
reach as an MIT project.

It might not make you money, but the reach of a successful open project
does wonders for exposure and credibility.

**Comment by gpgekko** [comment]
Seems #630 is relevant here

**Comment by meetbryce** [comment]
Thanks for the heads up Guylian. Went and posted my support for MIT

**Comment by jpolly168** [comment]
MIT would be great. Probably give a lot of people comfort to keep contributing as well.

**Comment by Klakurka** [comment]
I really can't endorse the project under the current license, and yet the work you've done is outstanding.

+1 for MIT.

**Comment by hsrob** [comment]
Looks like Federico did change the license to MIT. Hooray!

**Comment by kmmbvnr** [comment]
That's bad news for me. Project not looks very active in last 2 month, most commits are only contains trivial fixes. Many important things still not implemented.

It would be much better if author was motivated by good commercial selling price.

**Comment by jofftiquez** [comment]
Are you a god? Thanks.

**Comment by FezVrasta** [comment]
Unfortunately I've not a lot of time to dedicate on this project, I hope that releasing it under mit will incentive users to contribute

**Comment by Klakurka** [comment]
I'm sure it will!
Cheers!

**Comment by rosskevin** [comment]
MIT license committed.

**Comment by AtNovember** [comment]
I want to use 'bootstrap-material-design' with css-modules inside react components. 
but it also wants that i install jquery with this console message:

> Uncaught ReferenceError: jQuery is not defined

Propbably you already have any API for react components kind of 'react-bootstrap'? 
Or should I use some other method to include you library for styling?

Thank you, anyhow! very nice lib!

**Comment by Rajiv-Kulkarni** [comment]
I would be interested in using this library as a library of react components like the React-Bootstrap. Anyone?
