### ISSUE TITLE
Material Light

### ISSUE THREAD

**Issue by jonathanhecl** [mdbootstrap/mdb-ui-kit#433]
Hello!

I would like to remove some components to make it lighter.
I would remove the icons and colors. Because 1MB is very large.

Thanks!

**Comment by cattong** [comment]
css file is really too big, 1.0M, oh my god!

**Comment by FezVrasta** [comment]
It's already planned

**Comment by jonathanhecl** [comment]
Hello! I already did simplification!
I removed the MDI Icons and colors! now weighs 81 KB without minify! :100: 

http://pastebin.com/Hiq0WhxB

There were only two places where MDI Icon is used to display a navigation arrow to replace by Icons from Font Awesome and was perfect.

Hope that helps! :+1: 

EDIT: For the material colors, i download http://zavoloklom.github.io/material-design-color-palette/index.html (55 KB)
And add @import url("material-design-color-palette.min.css"); in the Material CSS.

Use like: mdc-bg-light-green-300

**Comment by gasolin** [comment]
81 KB without minify!  :+1:  PR please :)

**Comment by jonathanhecl** [comment]
I made a correction to use background "outside" colors on buttons. And besides adapting to bootstrap.css

.btn-bgdark:hover {
  color: rgba(255, 255, 255, 1);
}
.btn:not(.btn-link):not(.btn-flat):not(.btn-bg):not(.btn-bgdark),
.btn-default:not(.btn-link):not(.btn-flat):not(.btn-bg):not(.btn-bgdark) {
  background-color: transparent;
  color: rgba(255, 255, 255, 0.84);
  color: rgba(0, 0, 0, 0.84);
}

It is used (with material-design-color-palette.min.css colors) : btn-bgdark mdc-bg-blue

btn-bg = It allows us to put any background color or text without using the !Important. With BLACK hover default bootstrap.
btn-bgdark = It allows us to put any background color or text without using the !Important. With WHITE hover for dark backgrounds.

:8ball:

**Comment by GradyD** [comment]
Would you be open to creating a PR for this? I would love to see your code and what changes you have made. I have started working on removing the colors but if you have already done it that would make it a quick switch!

It would require a change in the workflow and adding https://github.com/zavoloklom/material-design-color-palette to the bower dependencies so that users can still build and assign a `@primary` color (since the colors would not be available OOTB). The other option would be to just include the color variables but not use them to mixin anything. 

Either way would be a step in the right direction so sharing your code will help speed things up.

**Comment by jonathanhecl** [comment]
Yes, I have already removed perfectly colors and icons, and in only two cases resorted to icons font awesome source, so this made it work.
Also the same with the dependence of "materials-design-Color-palette", also I have.
Also I made a fix to floating-label to be seen on the input (which came out below); (z-index: 2;)

This is the complete code: http://pastebin.com/Vm25YKPH

**Comment by GradyD** [comment]
Thanks for the CSS but do you mind sharing the LESS/SASS code for this or did you do it by hand?

In order make this future proof it needs a LESS or SASS file associated with it so that changes are not being managed by hand, waste of time and could cause mistakes, duplication, sloppy CSS, etc. 

Again thank you for doing this! It is a huge step forward for this project :+1:

**Comment by jonathanhecl** [comment]
Excuse me, but I did it by hand. :1234: 

Hope I can help us with this, at least the idea. :100:

**Comment by GradyD** [comment]
Haha, no worries. 

I have a PR submitted that will remove the icons. So we are moving in the right direction

**Comment by ronlobo** [comment]
Perfect :+1:

**Comment by lylepratt** [comment]
Any update on this?

**Comment by FezVrasta** [comment]
fixed with a4c09ab76ed95c8fe299530acf83b9a130576592
