### ISSUE TITLE
 package.js file: We were unable to parse your package.js file!

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#483]
I'm trying to enable the Auto Publish feature of Meteor but I get this error near the toggle button:

```
package.js file:
We were unable to parse your package.js file!
```

Any clue? @dandv

**Comment by guidouil** [comment]
Did you add the meteorpublish account as a maintainer for your meteor package ?
You have to use the terminal and go in your project and past this command to do it
`meteor admin maintainers fezvrasta:bootstrap-material-design --add meteorpublish`
Source : 
http://autopublish.meteor.com/howitworks

**Comment by FezVrasta** [comment]
I've added it but the error is still there.

**Comment by splendido** [comment]
That's a eval error on the package.js from the autopublish side :-(
I should switch to some regexp to pick up package's name and version. ..

In any case you should be able to enable it and see it as `Probably a Meteor package` among the subscriptions...

I'll have a look at it!

**Comment by splendido** [comment]
I've fixed the subscription for your `fezvrasta:bootstrap-material-design-noglyph`.

`Npm` is somewhat available inside the `packaje.js` file but not so polished: for example if you try to clone your repo and use it as a local package, it won't work because the current working directory won't be the root of the repo but that of the application you're running.
This is why I strongly suggest to integrate the version field update for the `package.js` file into a Grunt task.

This should lead to a clean

``` javascript
Package.describe({
  name: "fezvrasta:bootstrap-material-design-noglyph",
  summary: 'FezVrasta\'s Bootstrap Google Material Design theme. Material icons instead of Bootstrap glyphicons.',
  version: "0.2.1",
  git: 'https://github.com/fezvrasta/bootstrap-material-design.git'
});
```

At the next release the automated publish should work: let me know!

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
