### ISSUE TITLE
Card height to automatically fit content 

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#548]
Is this possible? The default card height code has a fixed height, very tall.

**Comment by FezVrasta** [comment]
Not currently... I should add some class to allow it.

**Comment by Streemo** [comment]
this needs to be implemented

**Comment by Streemo** [comment]
Is there a work around to make it that the card height isn't the same for all cards in a gallery? Cards with more content end up overflowing instead of stretching the card to be taller.

This card-height-indicator thing is very unintuitive. What is it? I'd rather control the height myself! I tried doing height: auto but it isn't working.

**Comment by Streemo** [comment]
Yeah, this was a silly design choice, imvHo. There is a fix. Get rid of the "card-height-indicator" hack and remove position:absolute for .card-content.

Hope this helps.

**Comment by rosskevin** [comment]
Note, cards have been added in bs4, whereas wells and panels were dropped.

http://v4-alpha.getbootstrap.com/migration/#components

**Comment by Zhigalin** [comment]
@rosskevin Please note that Bootstrap 4 is not production-ready. We mustn't rely on an alpha version.

**Comment by tilwinjoy** [comment]
Why does this have the `v3` label...? Bootstrap3 does not have cards at all... does Bootstrap material design 3 support cards?

**Comment by FezVrasta** [comment]
yes it has support for cards
