### ISSUE TITLE
material pagination buttons

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [mdbootstrap/mdb-ui-kit#589]
Hi!
why pagination buttons isn't designed with material!
how i can help with that?

**Comment by steffenf14** [comment]
i keeped on looking for a material designed pagiation, but wasn't able to find one since usually most material design apps/pages prefer infinite scroll. BUT there you go:

https://developers.google.com/web/updates/chrome/news/

![materialpagination](https://cloud.githubusercontent.com/assets/6428546/8117717/c3fa2d7e-108a-11e5-9569-5f48ee760c6a.JPG)

**Comment by irontiga** [comment]
There is also some nice pagination on this template. (Don't copy paste, but see how it looks)
https://wrapbootstrap.com/theme/material-admin-responsive-template-WB011H985

**Comment by FezVrasta** [comment]
I had this prototype ready but never had time to implement it

http://codepen.io/FezVrasta/pen/LExQYo

**Comment by irontiga** [comment]
never used github before to do the adding to repo think....i think i might have forked this repo with the pagination .less.....I fixed it up to us material pagination instead of bootstrap.....seems to work fine.

Anyway, this is the code i tried to add(it's less)...

`.pagination {
  text-align:center;
  font-family:'Roboto', sans-serif;
  padding:0;
  li {
    display:inline-block;
    list-style:none;
    width:40px;
    height:40px;
    border-radius:100%;
    overflow:hidden;
    position:relative;
    background:white;
    a {
      text-decoration:none;
      color:#ff4081;
      border:none;
      border:0;
      margin:0;
      padding:0;
      font-size:100%;
      font:inherit;
      line-height:40px;
      background-color:inherit;
      box-sizing:inherit;
      text-align:center;
      width:100%;
    }
    a:hover {
      color:#ff4081;
      background-color:#ffdee9;
    }
  }
  li:hover {
    background-color:#ff8ab2;
  }
  li.active {
    background:#c2185b;
    span {
      color:white;
    }
  }
  .active {
    a, a:hover, a:focus {
      color:white;
      background-color:inherit;
    }
    li {
      width:45px;
      height:45px;
    }
  }
  span {
    margin:5px;
    display:inline-block;
    width:30px;
    height:30px;
    text-align:center;
    line-height:30px;
    color:#ff4081;
  }
  a:active {
    color:#009587;
  }
  a:after {
    content:"";
    -webkit-transform:scale(0.2);
    -ms-transform:scale(0.2);
    transform:scale(0.2);
    opacity:0.2;
    display:block;
    width:40px;
    height:40px;
    position:absolute;
    top:0;
    border-radius:100%;
    background:rgba(0,0,0,0.1);
    -webkit-transition:-webkit-transform 0s ease-out 0.2s, opacity 0.2s ease-out 0s;
    transition:transform 0s ease-out 0.2s, opacity 0.2s ease-out 0s;
  }
  a:active:after {
    -webkit-transform:scale(1);
    -ms-transform:scale(1);
    transform:scale(1);
    opacity:1;
    -webkit-transition:-webkit-transform 0.2s ease-out, opacity 0.3s ease-out 0.1s;
    transition:transform 0.2s ease-out, opacity 0.3s ease-out 0.1s;
  }
}`

...actually i will make it again tomorrow with support for all the base mateial colors.

From the noobie who tries

**Comment by MahdiMajidzadeh** [comment]
@FezVrasta thanks! it's seems material :wink:

**Comment by rosskevin** [comment]
duplicate of #437
