### ISSUE TITLE
Button is shifiting down when combined with label etc

### ISSUE THREAD

**Issue by corientdev** [mdbootstrap/mdb-ui-kit#626]
``` html
<div class="col-md-12">
<div class="col-md-2">
Processing
</div>
<div class="col-md-4">
<button class="btn btn-primary">Hello</button>
</div>
</div>  
```

Outputs this

which clearly shows that button is shifted down
any fix?
![2015-06-25 17_40_35-bootstrap material](https://cloud.githubusercontent.com/assets/9655234/8353989/e1f22a02-1b61-11e5-90fa-487fe2c0574d.png)

**Comment by dmitryvmin** [comment]
Not sure if this is an issue with the library. Couple of things I noticed: 

First of all your boostrap mark up is incorrect. Your inner column set doesn't add up to 12 and needs to be wrapped in a row div. 

Second, I would check the styles that are applied to the "Processing" text. The more correct syntax for text would be to wrap it in a <p> or <span> div. I'm guessing the plain text is not getting any styling applied to it that otherwise would help it look vertically centered: line-height, top margin, top padding. 

Cheers

**Comment by corientdev** [comment]
I dont think issue is with mark up because after commenting the bootstrap material css its looking as desired with bootstrap css file

**Comment by rosskevin** [comment]
If this is still an issue, please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
