### ISSUE TITLE
radio-inline and checkbox-inline support

### ISSUE THREAD

**Issue by huiyiqun** [mdbootstrap/mdb-ui-kit#694]
radio-inline is not supported.

**Comment by arduanov** [comment]
and checkbox-inline  is not supported too

**Comment by rosskevin** [comment]
[Test case](http://codepen.io/rosskevin/pen/XmGGpG)

**Comment by rosskevin** [comment]
FYI the upcoming v4 has support for the inline elements, it's possible if someone wants to back-port it, but it could be time consuming even if it is not a lot of change...not sure, but a PR is requested if you want it.

**Comment by tilwinjoy** [comment]
@rosskevin I'd like to work on this issue, In fact I have the checkbox inline working in a playground. I went through the contribution guidelines, but the `grunt build` fails with the error `Warning: Task "build" not found. Use --force to continue.` Looking at the Gruntfile in master branch, I don't think there is a build task (_I might be wrong. I'm not familiar with grunt, I use gulp_). 

Directly running `grunt test` fails on `"sass:compile" (sass) task` with error 

```
Error: Invalid CSS after "        })": expected "{", was ";"
        on line 87 of sass/_buttons.scss
        from line 43 of sass/_core.scss
        from line 6 of sass/bootstrap-material-design.scss
```

I believe that's because of the build failure. I'm on a windows machine, I have installed grunt, ruby and sass. `npm install` and `bower install` went fine. Can you please help me with the initial hurdle..?

**Comment by rosskevin** [comment]
@tilwinjoy - great, go ahead.  The grunt task is now `grunt dist` or since it is defaulted, simply `grunt`.  

`grunt test` actually run's `grunt dist` first.

Sass is an auto-conversion, if it is giving you trouble, just stick to the `less` tasks when working on the source, and I can patch up the conversion...it really isn't worth anyone else needing to learn.

You should be able to bypass the sass by doing `grunt dist-less && grunt dist-js`.

Let me know if you have issues running those.

**Comment by tilwinjoy** [comment]
@rosskevin Any update on the `0.5.10` release?

**Comment by rosskevin** [comment]
Released
