### ISSUE TITLE
Integrate with Rails

### ISSUE THREAD

**Issue by sahilbabbar** [mdbootstrap/mdb-ui-kit#698]
How to integrate Bootstrap-Material-Design to Rails? 
The basic installation is through gem in Gemfile. What is the gem for MD?

**Comment by adrian-antonczyk** [comment]
Just paste into your Gemfile:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-bootstrap-material-design'
end
```

then run

``` bash
$ bundle install
```

then add into app/assets/stylesheets/application.css

``` ruby
 *= require bootstrap
 *= require bootstrap-material-design
```

and finall add into app/assets/javascript/application.js

``` ruby
//= require bootstrap
//= require bootstrap-material-design
```

it should work.

**Comment by awangdev** [comment]
Newly updated on 11.30.2015:
Instead of using `bootstrap-material-design`, I actually switched to [Angular Material Design](https://material.angularjs.org/latest/). Which might be a long-term solution to implement Google material design anyway. (In case that you are using angular as well :)

---

Or, in rails, when the source is from:

```
source 'https://rubygems.org'
gem 'bootstrap-sass', '>= 3.3.0'
gem 'bootstrap-material-design', '~> 0.2.2'
```

And also, sometimes when we can't do *= require bootstrap-material-design, we can also do the following to include scss:

```
@import "bootstrap-material-design/sass/material";
```

And depending on the version of bootstrap (for example i use bootstrap-sass), the keyword might be slightly different ; )

But overall, the material design can be easily added into rails. It's just, now my site is totally messed up, since material-design is converting the original bootstrap into some sort of new version :+1:

**Comment by rosskevin** [comment]
I strongly recommend switching to using bower to control your rails assets.  [Here is a writeup](http://stackoverflow.com/a/27791688/2363935) of how I did it.  It's a no-friction way of using all the bower components out there, and you don't need to worry about someone making a gem conversion (or an automated conversion).

In this manner, you can also access/override the less or sass file from bootstrap-material-design inside your rails project.
