### ISSUE TITLE
Error in: /sass/ripples.scss:29

### ISSUE THREAD

**Issue by jmaks1** [mdbootstrap/mdb-ui-kit#723]
opacity 1  instead 0.1

install from bower
"bootstrap-material-design": "~0.3.0"

**Comment by rosskevin** [comment]
Please update to 0.4.0

Sass is generated from the [_ripples.less file](https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/ripples.less#L30).  

Are you suggesting the value should be `1` instead of `0.1`?

I'm unclear on the issue what is the 'error'.  Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.

**Comment by rosskevin** [comment]
If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).

**Comment by jmaks1** [comment]
i'm using command:
bower i -S bootstrap-material-design
then downloaded "bootstrap-material-design": "~0.3.0"

in this version:
.ripple.ripple-on {
    opacity: 1;
}

**Comment by FezVrasta** [comment]
You should try the latest version. 4.0.1
