### ISSUE TITLE
Floating labels incorrect behavior inside .form-horizontal markup

### ISSUE THREAD

**Issue by iniva** [mdbootstrap/mdb-ui-kit#758]
Using version `0.5.2`

Example code with the behavior is here http://codepen.io/iniva/full/adbxWK/

With previous version I had no problem since the behavior was attached to a  `.floating-label` class used on inputs instead of the container div.

Is there a recommended implementation for floating labels inside a form horizontal markup?

So, my questions / suggestions:
- Can we use the `.label-floating` approach when the form has a default markup, i.e. one input per `.form-group`?
- And a `.floating-label` approach on each input when using a form horizontal, i.e. two or more inputs per `.form-group`?
- Or maybe isolate the floating labels behavior in a way that we avoid confusions with class names and / or implementations cases?

**Comment by rosskevin** [comment]
Thanks @iniva for the codepen, **very** helpful.

The main idea is to use the `.form-group` as the demarcation for a single label/input pair.  You show a valid bootlinted markup example.  

The workaround for the v3 compatible 0.5.\* versions ([and required markup for BS v4 since `.form-group` no longer mixes in `.row`](http://v4-alpha.getbootstrap.com/migration/#forms)) is to make the columns owned by rows, with the form-group inside the column.  So this change should be forward compatible and actually required for v4.

Here's a [working codepen](http://codepen.io/rosskevin/pen/obNKyO?editors=110), the only thing to iron out here would be either a column offset for spacing or some custom padding so that you can get some space.

Answers to questions:
1. yes, one label/input per form group (otherwise focus affects everything in the form-group)
2. no, only one input per form-group.  Even with the approach for v4, it's not likely to demarcate varied sets of markup automatically.  In v4, we still use `.form-group` as a signal, otherwise we guess and wrap the input alone.
3. floating labels are already pretty isolated, as long as you use one set of input/label/other markup per form-group 

On a related note, you might be happy to know that for the next major version v4's documentation samples are copied directly so I'm doing _everything_ I can to make default bootstrap markup work.

Please let us know if you have other questions

**Comment by iniva** [comment]
Thanks @rosskevin I saw your code, nice workaround. And yes , as you mentioned, this will be valid for v4 too.

I ended adding this custom css to achieve the spacing issue:

``` css
.form-horizontal .form-group.label-floating {
  margin-left: 0;
  margin-right: 0;
}
```

I updated the code at http://codepen.io/iniva/pen/adbxWK with that.

**Comment by rosskevin** [comment]
:+1:
