### ISSUE TITLE
Losing carets on build

### ISSUE THREAD

**Issue by suederade** [mdbootstrap/mdb-ui-kit#761]
I'm having trouble pinning down where the carets are being rendered from for dropdowns because something happens in my build process where they are gone after build. I'm minifying css and js into their respective files and copying all the fonts from the font folder and it seems to just vanish. Everything is styled correctly except there is no caret. Using v4.1.

**Comment by rosskevin** [comment]
@stevenmwade 

I'm busy with my own products and working on the v4-dev branch.  I don't have infinite time to give to this project or to personal support issues.  I have seen several issues from you and they [do not follow the contributing guidelines which include creating a codepen](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports).  Following these guidelines means doing your part for open source.  This is not a paid support issue tracker.
1. Please respect the time of others and reduce your issue to a test case so that others can quickly help you.
2. We are now on 0.5.3.  If you want help with 0.4.1 you are on your own, I suggest StackOverflow as suggested in the guidelines
3. This issue may be present in 0.5.3, but I'm busy working on the v4-dev branch.  If you provide a codepen test case that isn't working, I'll try to help and get it in a maintenance release.

Absent the above, I will close these issues as personal support requests.  Everyone needs to do their part, and your part is to contribute a refined codepen test case.

Thank you for your understanding.

**Comment by stevenmwade** [comment]
I can understand your frustration and if I could make a codepen, then I would, but I don't see a way to actually reproduce this in a codepen. Since I can't give you a build in a codepen, and there is a good amount of manipulation it is hard to find out where the caret comes from whether from a font or an image or what.

I am on 4.1 because I am not going to update everyday to accommodate 10 releases in two weeks and ones with class changes that would cause me to go through a good amount of code to change. I also don't see many changes in the area of the dropdown.

Since all I have done is minify the code and copy the fronts (which all work from what I can tell), I felt that this was the most appropriate place to ask where the source of the caret. I thought it could be a fairly simple answer from the one who contributed the code and I could find the answer on my own.

@rosskevin I'm sorry I misunderstand what an issue can actually consists of.

**Comment by rosskevin** [comment]
We are maintaining 0.5.x and the codepens correspond to that master version.  We are not maintaining 0.4.x; please do not submit issues related to an old version. 

You are free to use 0.4.x,  but you are on your own.
