### ISSUE TITLE
Most button types have lost their hover and active effects

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#763]
See http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#buttons. Only the flat buttons have a hover effect, and no button type has an active effect. This is especially inconvenient for the toolbar / button group elements, because there is no way to see which one is active.

**Comment by rosskevin** [comment]
These have definitely changed in 0.5.x since I did a review of the Material Design specification and MDL.

It is true that raised buttons do not have hover effects as per the [material design specification](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons).  It doesn't list a hover affect on the raised button for the light theme, though it does for the dark theme.

In looking at this again, I'm wondering if it is a typo?  I sort of see a color variation:

**EDIT** as I pasted it into github, I definitely see the variation since the image is enlarged:
![image](https://cloud.githubusercontent.com/assets/136564/11656657/47bcd548-9d7c-11e5-980d-dcce81b2de6e.png)

It is a missing attribute in the spec.

Regarding active states, I see the `.active` isn't matching, but `:active` is.

**Comment by rosskevin** [comment]
BTW - I'll look at this today, but it would help me greatly if you would refine this to a [codepen](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md) as requested in the contribution guidelines.

**Comment by FezVrasta** [comment]
Remember that the MD specs are mainly thought for mobile devices where the "hover" state doesn't exist. This doesn't mean that this project should ignore the "hover" state tho.

**Comment by gpgekko** [comment]
Ah, right, the active is specifically the `.active`. I didn't look further, since it wasn't working out for me and I had to revert.

**Comment by rosskevin** [comment]
[Test case](http://codepen.io/rosskevin/pen/bENxeG?editors=100)

**Comment by rosskevin** [comment]
Released in [0.5.4](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/v0.5.4)
