### ISSUE TITLE
Snackbar transitions have invalid '0' values

### ISSUE THREAD

**Issue by kurtextrem** [mdbootstrap/mdb-ui-kit#775]
https://github.com/FezVrasta/snackbarjs/blob/master/themes-css/material.css 
compare that with
the snackbar classes in bt-material. You'll notice, that the transition props have "0s" in the snackbarjs repo, while they have "0" here.
The latest Chrome marks the transition rule as invalid, if they have no unit behind the animation time.

**Comment by rosskevin** [comment]
I did a search on the codebase, and found no instances where transition was marked as `0` and not `0s`.  The only instances of transitions with a 0s value were in inputs, and ripples.  Since you only reference "here", I have no idea which code you are referring to.  Perhaps you are on an older version?

**Comment by FezVrasta** [comment]
I think "here" is https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/plugins/_plugin-snackbarjs.less

**Comment by rosskevin** [comment]
As in `height 0`?

**Comment by rosskevin** [comment]
I see it now.
