### ISSUE TITLE
Material-icons dissapearing

### ISSUE THREAD

**Issue by aminhusni** [mdbootstrap/mdb-ui-kit#825]
1. Inserted icons using 
   `<i class="material-icons">accessibility</i>`
2. Resized bootstrap grid which has the icon inside.
3. Icon disappear across all pages. 
4. I copy my source into a new working file with fresh files for bootstrap material design.  
5. The icon appears again as normal/previously. 
6. Adjust size of grid again just to double check/recreate the problem. 
7. Person disappears permanently on all pages. 

Current workaround: 
Used 
`<i class="material-icons">&#xE84E;</i>`
instead of
`<i class="material-icons">accessibility</i>`

*Applies to all of the icons.

**Comment by rosskevin** [comment]
`.material-icons` is a style provided by:

```
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

If you follow that link you'll see the style:

```
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

It has no `min-width` or `min-height`, and BS3 grids (also not provided by this project) may not recognize something with a zero dimension (just my guess).

BS3 uses glyphicons, but with `content: "\002a"` for example, which is similar to your 'workaround'.

With all of these things said, I don't see this as a bootstrap-material-design 'bug' and I'm not sure we can provide a general solution i.e. I don't think a `min-width | min-height` is something that could be included without side effects.  Perhaps I'm incorrect, but that is my estimation.

I would not suggest using codes as a workaround instead of ligatures because they are hard to use/understand.  

I would suggest some custom css for your situation and you add `min-height` and `min-width` to ensure they appear.
