### ISSUE TITLE
v4 dist folder not in repo

### ISSUE THREAD

**Issue by pinx** [mdbootstrap/mdb-ui-kit#837]
In the "getting started" 
http://rosskevin.github.io/bootstrap-material-design/getting-started/introduction/
there's a reference to
https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/v4-dev/dist/css/bootstrap-material-design.css
but the 'dist' folder no longer exists in the v4-dev branch.

**Comment by rosskevin** [comment]
I've committed one now that we have some reasonable amount of things working.  

FYI - Given the new method of customization, you are _very_ likely to need to customize the variables using SCSS instead of using the general dist file with at least `$brand-primary`, so much so that I've even considered leaving out a `.css` in the dist.  But for now it is planned to be generated and provided.

**Comment by pinx** [comment]
The library has been working pretty well.
For me, I just want a quick and easy way to make my app familiar to my users. I don't want to do any customizations. Just dropping in a ref to a cdn link is what I want. I hope you are not planning to take that away.
I have switched from materializecss to this lib.

**Comment by dionysiosarvanitis** [comment]
Isn't it time to have a dist directory? Or is there any other alternative to have the dist version without manual compiling it? NPM or cdn?

**Comment by FezVrasta** [comment]
Still waiting for Bootstrap to wake-up and let know the official release date...
