### ISSUE TITLE
v4 doc on using with brunch

### ISSUE THREAD

**Issue by pinx** [mdbootstrap/mdb-ui-kit#847]
I'm using the Phoenix/Elixir framework, which uses brunch for it's assets.
The key things that got it working for me:
- in package.json add:
  "sass-brunch": "^1.9.2",
- in bower.json add:
  "dependencies": { "bootstrap-material-design": "v4-dev" }
- in brunch-config.js add under plugins:
  sass: { options: { includePaths: [ 'bower_components' ] } }
- change web/static/app.css to .scss and add:
  @import 'bootstrap-material-design/scss/bootstrap-material-design';

I would like to be able to import only parts of bootstrap-material-design, to keep my mobile app small. I hope that's possible with @import.

**Comment by rosskevin** [comment]
http://rosskevin.github.io/bootstrap-material-design/getting-started/customization/
- IMPORTANT: If you want to customize anything, be sure to import `core` instead of `bootstrap-material-design`.  You must import an underscored file to retain an unbroken context for variables.
- you can use bower or npm, both will work with repo branches, but the `includePaths` would be different

You can import anything you like, you have the source, though it doesn't seem to me that this sample has any problem importing the full css. I wouldn't be so quick to assume that this is inefficient and you should try to pair down what you are importing.  Certainly, if you don't use features then by all means, but don't get caught in premature optimization.

See how this performs on your target mobile:
http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

Please feel free to start a brunch wiki page and update your info.

**Comment by rosskevin** [comment]
BTW - I just looked, and the minified css (which includes bootstrap itself) is 268kb.  Granted I have a nexus6p, but we tested the dashboard example on several devices and optimized scrolling, it seems to work pretty well.

**Comment by pinx** [comment]
I haven't done any thorough testing, but I'm guessing that on old devices, any css animations or javascript slows things down. For some parts of my app, I don't need those, so I am looking to have a decent look (and less of the feel).

**Comment by rosskevin** [comment]
Try out http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

It has all of those.

**Comment by pinx** [comment]
I was getting compilation errors, so I dropped the whole source code in my assets folder. I still got a few error messages (a path not found, then a variable not defined). I fixed those, and now it more or less works.
