### ISSUE TITLE
Choose different colour theme from meteor package

### ISSUE THREAD

**Issue by ndastur** [mdbootstrap/mdb-ui-kit#885]
Is there a way to choose a different colour theme when using the meteor package? I tried creating my own .less files with the relevant variables, but that didn't work.
Thanls

**Comment by rosskevin** [comment]
Please use StackOverflow for personal support questions.  This is for bugs/issues/enhancements.

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md

**Comment by ndastur** [comment]
Sorry, maybe I phrased it incorrectly. Using the meteor package there isn't any config available. So really can I open this as an issue?

**Comment by rosskevin** [comment]
Note that none of the maintainers use meteor, please keep that in mind.

Why would you need a config? (honest question, I really don't know why you need one)

**Comment by ndastur** [comment]
Thank you @rosskevin . That is worth bearing in mind about meteor use.

In the documentation, it says the colour palette can be customised (that is the bit I am currently interested in). There are various methods described and the most appropriate to meteor seemed to be to customise via less variables. But this doesn't work. 

Looking at https://github.com/Nemo64/meteor-bootstrap it seems some special customisation code might be required in the meteor package itself.

**Comment by rosskevin** [comment]
That is something that Nemo64 provided, a repackaging of bootstrap itself for meteor.  Something like that would definitely be out of the scope of _this_ project.  This project is focused on less/sass/js itself, not providing customized configurations for a deployment/package system.  For example, our bower/npm packages are simply metadata about our source/dist files, and that is the same way we treat meteor.

On customization, we expect that users will want to customize colors:
https://github.com/FezVrasta/bootstrap-material-design#customization

I would _expect_ meteor to allow you to override less or sass variables that override less or sass source files.  If not, then that's a serious meteor issue.  Given the link you provided, perhaps it doesn't allow it and it is a serious meteor problem?  **I honestly have no idea**.

What I do know is that _this_ is not a meteor project.  It is a less/sass/js project that is exposed as npm/bower/meteor packages.

If you want to start a companion project that repackages MDB for meteor with a similar type of configuration, we would be happy to point users to it!  In fact, I wouldn't be adverse to taking meteor support out of _this_ if a proper meteor package published a healthy version of MDB.

The reason we considered pulling the meteor package is that we want a first class representation of the project out there in all respects, and it appears the meteor ecosystem differs a bit in approach from everyone else, so is our package _first class_?  Again **I have no idea** because I don't use meteor but I doubt it.

Is anyone interested in creating a first class meteor package project for MDB?  If so, please step up.

**Comment by ndastur** [comment]
@rosskevin thank you for the detailed reply. And I get the ethos of your project. When I get more familiar with meteor I will try and take a look at a companion project.

Can I just check? You refer to MDB. Is this the same project as http://mdbootstrap.com/material-design-for-bootstrap/ ??

**Comment by rosskevin** [comment]
No, that's something else.  We've called this `Material Design for Bootstrap` for some time, a.k.a MDB or MD4B.  I have no idea what files that site is providing...seems like an unfortunate naming conflict.
