### ISSUE TITLE
Meteor - failed to parse sourcemap

### ISSUE THREAD

**Issue by johhansantana** [mdbootstrap/mdb-ui-kit#917]
![screenshot from 2016-03-16 10 08 11](https://cloud.githubusercontent.com/assets/9933887/13814971/0ef06870-eb5f-11e5-969d-30d3ab28e577.png)

I installed this package on meteor using atmosphere and I get these errors, the style works but I keep getting these.

**Comment by FezVrasta** [comment]
Have you included the source maps? :)

**Comment by rosskevin** [comment]
@jsantana90 if the sourcemaps aren't included in the package, you'll need to submit a PR to include them and I can re-publish.  

The maintainers don't use meteor so we are relying on our meteor users to provide the support for this package (otherwise we have considered removing the meteor package).  If you aren't willing to submit a PR, I'll probably go ahead and close this as I don't want abandoned (issues without a contributor) in the repo.

**Comment by jsantana90** [comment]
Doesn't atmosphere package takes care of that?  If not, where do I get them?

**Comment by rosskevin** [comment]
I'm guessing they should be in the package, if not, you'll need to submit a PR to modify the build process to include them.  If you aren't going to submit a PR, please let me know.

**Comment by johhansantana** [comment]
I'm not sure how to update the meteor packages as I've never done it before. I have removed the package from my meteor app and tried adding it with bower, but ended with the same result.

**Comment by tizol** [comment]
@jsantana90 @rosskevin
The recent version of Chrome added support for source maps in the developer tools. 
1. Go under settings while in developer toolbar 
2. **_Disable_** 
3. [ ] Enable JavaScript source maps
4. [ ] Enable CSS source maps

As shown in the image. This should fix the source map error

![screen shot 2016-07-01 at 3 11 28 pm](https://cloud.githubusercontent.com/assets/6495684/16535679/2cf1fc06-3f9e-11e6-8e16-537dc839bc76.png)
