### ISSUE TITLE
Multiple help-block elements on a field overwrite each other

### ISSUE THREAD

**Issue by sanderman123** [mdbootstrap/mdb-ui-kit#926]
When using bootstrap-material-design in combination with Django. I found that when there are multiple elements with the class "help-block" rendered for a field, they will be rendered on top of each other. 

You can find the issue reproduced here:
http://codepen.io/sanderman123/pen/BKWqXg

For Django this really is an issue, because for instance when a user registers and forget's to enter a user-name, Django's registration will give 2 error messages.
When just using plain bootstrap, both messages are displayed normally, like this:
![screen shot 2016-03-21 at 9 14 10 pm](https://cloud.githubusercontent.com/assets/5829899/13932794/3050a260-efaa-11e5-80c5-0a32eed651ef.png)

Using bootstrap-material-design, the messages are rendered like this:
![screen shot 2016-03-21 at 9 12 01 pm](https://cloud.githubusercontent.com/assets/5829899/13932697/b843c86a-efa9-11e5-857f-7d1db7c33033.png)

I really love it that I can use material design with bootstrap so thanks a lot for the hard work! Hope this issue will be easy to resolve for you guys :)

**Comment by rosskevin** [comment]
Refined case http://codepen.io/rosskevin/pen/XdMyNe

This is expected because we use:

``` css
.form-group .help-block {
    position: absolute;
}
```

This is a tradeoff to prevent bouncing on focus with floating labels etc.  View the following and in your debugger disallow this rule then go through the fields, you will see the page bounce with each hint showing.  http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#forms

I'm open to alternatives, if you have a good one that prevents the bouncing but doesn't require `absolute`, please let me know.

Otherwise, you can choose to override this in your stylesheet and set it to `position: relative`

**Comment by sanderman123** [comment]
Thanks for the swift response!
I'm not really a CSS wizard, but this little hack at least solves the issue in case of 2 help-blocks:
http://codepen.io/sanderman123/pen/eZvbWQ

```
.form-group .help-block:nth-of-type(2) {
    position: relative;
    padding-top: 1.2em;
    margin-bottom: -2.6em;
}
```

What it looks like in case of Django registration forms:
http://codepen.io/sanderman123/pen/vGxvJK

**Comment by SergeyKhval** [comment]
@sanderman123 
[This pen](http://codepen.io/transGLUKator/pen/yOMrQG) solves the problem when there are more than 2 help blocks, thought it is still a bit ugly in terms of bouncing inputs

**Comment by rosskevin** [comment]
@SergeyKhval I've added your code to v4
