### ISSUE TITLE
How to use Selectize.js with bootstrap material design.

### ISSUE THREAD

**Issue by vinod27ece** [mdbootstrap/mdb-ui-kit#967]
Hi,

Currently I have included Selectize.js from github and it is not looking as user friendly, So do material design provide default Selectize functionality, or can you suggest a replacement for that with filter in select element.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design#selectizejs

**Comment by Jomari-Macaraig** [comment]
Hi,

I have a similar question. How do we integrate selective.js with bootstrap material design?

https://github.com/FezVrasta/bootstrap-material-design#selectizejs - Says (correct me if I'm wrong) don't include the CSS of the plugin because the material design will replace its CSS.

Can you give an example on how to integrate this ?

Sorry for the stupid/newbie question.
