### ISSUE TITLE
Disabled Checkbox shows wrong cursor on hover

### ISSUE THREAD

**Issue by derwok** [mdbootstrap/mdb-ui-kit#989]
Using V3...
#### Test Case

Embedd material bootstrap checkbox in HTML, call $material.init();
Hover mouse over DISABLED checkbox (label or box).

See codepen:
http://codepen.io/derwok/pen/QNJoaZ

See screen shot:
![disabledcheckbox](https://cloud.githubusercontent.com/assets/4393698/14986001/569b4724-114a-11e6-9121-c97ffe3d7a2e.png)
#### Summary

Mouse cursor shows "pointer" symbol on disabled and not-disabled checkboxes
#### Expected result

Mouse pointer should show "default" symbol on disabled

**Comment by tilwinjoy** [comment]
@rosskevin Should disabled form controls show default cursor? bootstrap uses  `not-allowed`, does material design spec say otherwise?

**Comment by rosskevin** [comment]
Not allowed must be mistakenly picked up from disabled somewhere.

**Comment by tilwinjoy** [comment]
@rosskevin Not sure what you mean. I was referring to [bootstrap official form controls page](http://getbootstrap.com/css/#forms-controls). It uses `not-allowed` cursor for disabled checkbox and radio. So unless material spec says otherwise we should follow bootstrap right? I think it's meaningful to show `not-allowed` than normal cursor for form controls...

**Comment by rosskevin** [comment]
Yes

**Comment by tilwinjoy** [comment]
@rosskevin I'll make a PR for this
